version: "3"

services:
  test:
    build: ./api_server
    ports: 
      - "3001:3001"
    volumes:
      - "./api_server:/usr/src/app"
      - "api_server_cargo:/usr/local/cargo"
    command: "cargo watch -x test"

volumes:
  api_server_cargo:
