[package]
name = "solver"
version = "0.1.0"
authors = ["Matt Burke <spraints@gmail.com>"]
edition = "2018"
description = "Advent of Code 2020 solutions as WASM"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
